name: Build and Deploy

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm build

      - name: Push build to build branch
        run: |
          COMMIT_SHA=$(git rev-parse --short HEAD)

          cd dist

          git init
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout --orphan build
          git add .
          git commit -m "build: update from ${COMMIT_SHA}"
          git remote add origin https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}.git
          git push origin build --force

